"""add_address_table

Revision ID: 648a47f4a6aa
Revises: bc150f39462a
Create Date: 2023-04-05 13:39:02.240747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '648a47f4a6aa'
down_revision = 'bc150f39462a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Address',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('country', sa.String(length=56), nullable=False),
    sa.Column('city', sa.String(length=21), nullable=False),
    sa.Column('district', sa.String(length=15), nullable=False),
    sa.Column('ward', sa.String(length=15), nullable=False),
    sa.Column('street', sa.String(length=15), nullable=False),
    sa.Column('numbers_home', sa.String(length=15), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numbers_home')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Address')
    # ### end Alembic commands ###
