"""add_role_table

Revision ID: 017365b4fe9f
Revises: 630b32228127
Create Date: 2023-04-05 13:38:04.635511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '017365b4fe9f'
down_revision = '630b32228127'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Role',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Enum('ADMIN', 'CUSTOMER', 'OWNER', name='roleenum'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Role')
    # ### end Alembic commands ###
